import "./global.css";
import Navbar from "@/component/shared-component/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
      </head>
      <body className="font-sans">
        <div className="flex min-h-screen">
          <aside
            className="w-64 flex flex-col justify-center items-center"
            style={{ backgroundColor: '#FAF9F8', minHeight: '100vh' }}
          >
            <Navbar />
          </aside>
          <main className="flex-1 p-6" style={{ backgroundColor: '#FAF9F8' }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
