import "./global.css";
import Navbar from "@/component/shared-component/Navbar";
import Link from "next/link"; // Required for client-side routing

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body className="font-sans bg-[#FAF9F8]">
        <div className="flex min-h-screen flex-col sm:flex-row">
          {/* Sidebar (only on desktop) */}
          <aside className="hidden sm:flex w-64 flex-col justify-center items-center bg-[#FAF9F8]">
            <Navbar />
          </aside>

          {/* Main Content */}
          <main className="flex-1 p-4 sm:p-6 mb-16 sm:mb-0">{children}</main>

          {/* Bottom Navbar (only on mobile) */}
          <nav className="fixed bottom-0 left-0 w-full bg-white shadow-md flex justify-around py-3 sm:hidden z-50">
            <Link href="/" className="text-gray-700 hover:text-blue-600 text-center">
              <span
                className="material-symbols-outlined hover:scale-125 transition-transform duration-300"
                style={{ fontSize: "30px" }}
              >
                home
              </span>
            </Link>
            <Link href="/user/about" className="text-gray-700 hover:text-blue-600 text-center">
              <span
                className="material-symbols-outlined hover:scale-125 transition-transform duration-300"
                style={{ fontSize: "30px" }}
              >
                contacts
              </span>
            </Link>
            <Link href="/user/project" className="text-gray-700 hover:text-blue-600 text-center">
              <span
                className="material-symbols-outlined hover:scale-125 transition-transform duration-300"
                style={{ fontSize: "30px" }}
              >
                shopping_bag
              </span>
            </Link>
          </nav>
        </div>
      </body>
    </html>
  );
}
